### ISSUE TITLE
Code Ghost Theme

### ISSUE THREAD

**Issue by mbejda** [HowtoGhost/allghostthemes#82] opened 2016-01-10 17:33 UTC
### Theme Name

Code Ghost Theme

### Theme Description

Theme designed to showcase technology projects

### Link to your live demo

http://mbejda.com

### Link to download/purchase page

https://github.com/mbejda/CoderGhostTheme

### Number of columns

2

**Comment by andyboutte** [comment] 2016-02-26 06:08
Duplicate of issue #78

**Closed by andyboutte** 2016-02-26 06:08 UTC
